### ISSUE TITLE
Error while building release apk

### ISSUE THREAD

**Issue by henriquejnmarques** [appspector/flutter-plugin#10]
This happens after upgrading flutter sdk to v1.7.

```
file:///home/cirrus/.pub-cache/hosted/pub.dartlang.org/appspector-0.0.5/lib/src/http/response_wrapper.dart:4:7: Error: The non-abstract class 'HttpResponseWrapper' is missing implementations for these members:
 - HttpClientResponse.compressionState
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class HttpResponseWrapper extends StreamView<List<int>>
      ^^^^^^^^^^^^^^^^^^^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:1967:42: Context: 'HttpClientResponse.compressionState' is defined here.
  HttpClientResponseCompressionState get compressionState;
                                         ^^^^^^^^^^^^^^^^
```

**Comment by sergeyzenchenko** [comment]
Hi @henriquejnmarques thanks for feedback. This issue is fixed and we are preparing new release. I will let you know when it's available.

**Comment by Dimdron** [comment]
Hi @henriquejnmarques, please could you try new plugin version 0.0.6 ?

**Comment by henriquejnmarques** [comment]
Sorry for the delay, I already tested it and I could not do the apk build.

Error:
```dart
flutter build apk --release
You are building a fat APK that includes binaries for android-arm, android-arm64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Initializing gradle...                                              0,8s
Resolving dependencies...                                           5,0s

Compiler message:
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/appspector-0.0.6/lib/src/http/response_wrapper.dart:5:7: Error: 'HttpResponseWrapper' can't implement both 'Stream<Uint8List>' and 'Stream<List<int>>'
 - 'Stream' is from 'dart:async'.
 - 'Uint8List' is from 'dart:typed_data'.
 - 'List' is from 'dart:core'.
class HttpResponseWrapper extends StreamView<Uint8List>
      ^
Compiler terminated unexpectedly.                                       
                                                                        
FAILURE: Build failed with an exception.
```

**Comment by Dimdron** [comment]
Hi @henriquejnmarques, which version of dart and flutter do you use?

**Comment by Dimdron** [comment]
Please, try to update dart in your `pubspec.yaml`. I mean `environment: sdk: ">=2.3.1-dev.1.0 <3.0.0"`

**Comment by henriquejnmarques** [comment]
```dart
Flutter 1.7.8+hotfix.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b712a172f9 (13 days ago) • 2019-07-09 13:14:38 -0700
Engine • revision 54ad777fd2
Tools • Dart 2.4.0
```

**Comment by Dimdron** [comment]
@henriquejnmarques did you try to update Dart SDK in your `pubspec.yaml`? Usually, it resolves the problem.

**Comment by henriquejnmarques** [comment]
For me it didn't work. I upgraded packages with the ```flutter upgrade``` command after changing the ```pubspec.yaml``` file. Below I show the project dependencies, maybe you can find something.
```yaml

environment:
  sdk: ">=2.3.1-dev.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # custom dependencies
  http: ^0.12.0+2
  hidden_drawer_menu: ^1.0.0
  json_annotation: ^2.0.0
  flutter_gherkin: ^1.0.4
  appspector: ^0.0.6
  f_logs: ^1.1.1
  font_awesome_flutter: any
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  # util para "One-time code generation"
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  test: any
  mockito: any

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
```
